kind: pipeline
name: gitbook

steps:
  - name: test   
    image: centos-node-8-12-0
    commands:     
      - npm install gitbook -g
      - gitbook install
      - gitbook serve .
   
  - name: build
    image: centos-node-8-12-0
    commands:     
      - npm install gitbook -g
      - gitbook install
      - gitbook build . ./docs
 
  - name: publish
    image: centos-node-8-12-0
    environment:
      USERNAME:
        from_secret: git_username
      PASSWORD:
        from_secret: git_password
    commands: 
      - yum install git -y
      - git add .
      - git commit -a -m "drone push"
      - git remote add github https://github.com/sakurayang/Document.git
      - git push -u origin master
      - git push -u github master