kind: pipeline
name: gitbook

steps:
  - name: test   
    image: node
    commands:     
      - npm install gitbook -g
      - gitbook install
      - gitbook serve .
   
  - name: build
    image: node:latest
    commands:     
      - npm install gitbook -g
      - gitbook install
      - gitbook buil . ./docs
 
  - name: publish
    image: plugins/github-release
    settings:
      api_key: a0cad4a3fb8896010452222017c350dad183e9e8
      files: *